### ISSUE TITLE
No window.navigator present in getWindow() (need getNavigator()?)

### ISSUE THREAD

**Issue by phun-ky** [darrylwest/mock-browser#1]
I came across mock-browser in attempt to mock up the global methods used in browsers to test my clientside code in NodeJS with jasmine.

I've already sorted the provided stuff from mock-browser, but I see that you have nothing to mock up navigator with? Is this feature deliberately ommited? forgotten? to come?

**Comment by darrylwest** [comment]
hi @phun-ky ,

Yes, this was an oversight.   It is available in version 00.90.33.  thanks for catching it.

-- darryl
